import '../models/models.dart';

class DataService {
  static final List<Category> categories = [
    const Category(id: 'food', name: 'Makan', nameId: 'Kuliner', emoji: '🍜', colorValue: 0xFFFFF3F0),
    const Category(id: 'cafe', name: 'Kafe', nameId: 'Kafe & Minuman', emoji: '☕', colorValue: 0xFFE8F8F2),
    const Category(id: 'shopping', name: 'Belanja', nameId: 'Shopping', emoji: '🛍️', colorValue: 0xFFF0EEFF),
    const Category(id: 'entertainment', name: 'Hiburan', nameId: 'Hiburan', emoji: '🎭', colorValue: 0xFFFFF8E8),
    const Category(id: 'nature', name: 'Wisata', nameId: 'Wisata Alam', emoji: '🌿', colorValue: 0xFFEDF8E4),
    const Category(id: 'spa', name: 'Spa', nameId: 'Spa & Wellness', emoji: '💆', colorValue: 0xFFFFF0F5),
    const Category(id: 'nightlife', name: 'Malam', nameId: 'Kehidupan Malam', emoji: '🎵', colorValue: 0xFFEAF4FF),
  ];

  static final List<Place> places = [
    Place(
      id: 'p001',
      name: 'Sate Khas Senayan',
      category: 'food',
      subcategory: 'Masakan Indonesia',
      address: 'Jl. Kebon Sirih No.31A, Menteng',
      district: 'Jakarta Pusat',
      latitude: -6.1892,
      longitude: 106.8229,
      rating: 4.8,
      reviewCount: 2341,
      priceRange: 'Rp 80k – 150k',
      openHours: '10:00 – 22:00',
      isOpen: true,
      isFeatured: true,
      imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
      images: [
        'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
        'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
      ],
      phone: '+62 21 3143695',
      description: 'Restoran sate legendaris Jakarta yang telah berdiri sejak 1968. Terkenal dengan sate ayam dan sate kambing berbumbu kacang khas yang tak tertandingi.',
      tags: ['Legendaris', 'Halal', 'Family Friendly', 'Parkir Tersedia'],
      distanceKm: 1.2,
      amenities: ['Parkir', 'AC', 'WiFi', 'Halal', 'Kartu Kredit'],
      reviews: [
        Review(
          id: 'r001', userId: 'u1', userName: 'Budi Santoso',
          userAvatar: 'https://i.pravatar.cc/100?img=1',
          rating: 5.0, comment: 'Sate terenak di Jakarta! Bumbu kacangnya khas banget.',
          date: DateTime(2024, 3, 15), helpfulCount: 42,
        ),
      ],
    ),
    Place(
      id: 'p002',
      name: 'Tanamera Coffee SCBD',
      category: 'cafe',
      subcategory: 'Specialty Coffee',
      address: 'Pacific Place Mall Lt.1, SCBD',
      district: 'Jakarta Selatan',
      latitude: -6.2248,
      longitude: 106.8094,
      rating: 4.7,
      reviewCount: 1876,
      priceRange: 'Rp 50k – 90k',
      openHours: '08:00 – 22:00',
      isOpen: true,
      isFeatured: true,
      isNew: false,
      imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800',
      images: [
        'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
      ],
      phone: '+62 21 5140 5555',
      description: 'Specialty coffee dari biji kopi terbaik Nusantara. Roastery sendiri dengan barista berpengalaman.',
      tags: ['Specialty Coffee', 'Cozy', 'Remote Work'],
      distanceKm: 0.8,
      amenities: ['WiFi Cepat', 'Stop Kontak', 'AC', 'Kartu Kredit'],
    ),
    Place(
      id: 'p003',
      name: 'Grand Indonesia',
      category: 'shopping',
      subcategory: 'Luxury Mall',
      address: 'Jl. MH Thamrin No.1, Menteng',
      district: 'Jakarta Pusat',
      latitude: -6.1953,
      longitude: 106.8218,
      rating: 4.6,
      reviewCount: 15234,
      priceRange: 'Beragam',
      openHours: '10:00 – 22:00',
      isOpen: true,
      isFeatured: true,
      imageUrl: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800',
      phone: '+62 21 2358 0200',
      description: 'Pusat perbelanjaan premium terbesar di Jakarta dengan lebih dari 500 tenant fashion, kuliner, dan hiburan.',
      tags: ['Luxury', 'International Brand', 'Food Court'],
      distanceKm: 3.5,
      amenities: ['Parkir Luas', 'ATM', 'Food Court', 'Bioskop', 'Playground'],
    ),
    Place(
      id: 'p004',
      name: 'Ancol Dreamland',
      category: 'entertainment',
      subcategory: 'Taman Hiburan',
      address: 'Jl. Lodan Timur No.7, Ancol',
      district: 'Jakarta Utara',
      latitude: -6.1248,
      longitude: 106.8344,
      rating: 4.5,
      reviewCount: 8932,
      priceRange: 'Rp 30k – 300k',
      openHours: '07:00 – 24:00',
      isOpen: true,
      isFeatured: true,
      imageUrl: 'https://images.unsplash.com/photo-1513051265668-cff3d44e84b4?w=800',
      phone: '+62 21 6414 3333',
      description: 'Kawasan rekreasi tepi pantai terbesar di Asia Tenggara. Lengkap dengan Dunia Fantasi, Sea World, dan pantai.',
      tags: ['Keluarga', 'Pantai', 'Wahana Air', 'Weekend'],
      distanceKm: 8.2,
      amenities: ['Parkir Luas', 'Restoran', 'Pantai', 'Hotel', 'ATM'],
    ),
    Place(
      id: 'p005',
      name: 'Ame Spa Kuningan',
      category: 'spa',
      subcategory: 'Luxury Spa',
      address: 'Ascott Kuningan 10th Floor, Jl. Prof. DR. Satrio',
      district: 'Jakarta Selatan',
      latitude: -6.2249,
      longitude: 106.8241,
      rating: 4.9,
      reviewCount: 237,
      priceRange: 'Rp 300k – 800k',
      openHours: '10:00 – 23:00',
      isOpen: true,
      isFeatured: true,
      imageUrl: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800',
      phone: '+62 819-0330-6668',
      description: 'Spa mewah bertema Bali di jantung Jakarta. Suasana tenang, terapis berpengalaman, dan fasilitas bintang lima.',
      tags: ['Luxury', 'Bali Vibes', 'Couple Package', 'Deep Tissue'],
      distanceKm: 1.5,
      amenities: ['Private Room', 'Couple Room', 'Shower', 'Locker', 'Herbal Tea'],
      reviews: [
        Review(
          id: 'r005', userId: 'u5', userName: 'Dewi Rahayu',
          userAvatar: 'https://i.pravatar.cc/100?img=5',
          rating: 5.0, comment: 'Seperti berwisata ke Bali! Terapis sangat profesional.',
          date: DateTime(2024, 4, 2), helpfulCount: 28,
        ),
      ],
    ),
    Place(
      id: 'p006',
      name: 'Potato Head Beach Club',
      category: 'nightlife',
      subcategory: 'Rooftop Bar',
      address: 'SCBD Lot 12, Jl. Jend Sudirman',
      district: 'Jakarta Selatan',
      latitude: -6.2267,
      longitude: 106.8076,
      rating: 4.6,
      reviewCount: 3210,
      priceRange: 'Rp 150k – 500k',
      openHours: '17:00 – 02:00',
      isOpen: false,
      isFeatured: true,
      imageUrl: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800',
      phone: '+62 21 2999 2800',
      description: 'Rooftop bar ikonik dengan pemandangan skyline Jakarta. DJ internasional setiap akhir pekan.',
      tags: ['Rooftop', 'DJ', 'Cocktails', 'Dress Code'],
      distanceKm: 3.8,
      amenities: ['Dress Code Required', 'Valet Parking', 'VIP Table', 'Full Bar'],
    ),
    Place(
      id: 'p007',
      name: 'Taman Suropati',
      category: 'nature',
      subcategory: 'Taman Kota',
      address: 'Jl. Taman Suropati, Menteng',
      district: 'Jakarta Pusat',
      latitude: -6.2031,
      longitude: 106.8385,
      rating: 4.4,
      reviewCount: 4521,
      priceRange: 'Gratis',
      openHours: '06:00 – 18:00',
      isOpen: true,
      imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
      phone: '-',
      description: 'Taman kota bersejarah di kawasan Menteng. Hijau, asri, dan penuh patung karya seniman ASEAN.',
      tags: ['Gratis', 'Jogging', 'Fotografi', 'Sejarah'],
      distanceKm: 4.1,
      amenities: ['Jogging Track', 'Bangku Taman', 'Toilet Umum'],
    ),
    Place(
      id: 'p008',
      name: 'Serene Wellness Sampoerna',
      category: 'spa',
      subcategory: 'Reflexology & Lymphatic',
      address: 'Sampoerna Strategic Square LG, Jl. Sudirman 45-46',
      district: 'Jakarta Selatan',
      latitude: -6.2170,
      longitude: 106.8184,
      rating: 5.0,
      reviewCount: 1220,
      priceRange: 'Rp 150k – 400k',
      openHours: '08:00 – 22:00',
      isOpen: true,
      isFeatured: true,
      isNew: false,
      imageUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800',
      phone: '+62 812-1000-9237',
      description: 'Spesialis lymphatic massage dan reflexology dengan rating sempurna. Terapis terlatih, suasana bersih dan tenang.',
      tags: ['Rating Tertinggi', 'Lymphatic', 'Reflexology', 'Waxing'],
      distanceKm: 2.0,
      amenities: ['Private Room', 'Waxing Room', 'Locker', 'Shower'],
    ),
    Place(
      id: 'p009',
      name: 'Nusantara Kitchen',
      category: 'food',
      subcategory: 'Fine Dining',
      address: 'Jl. Senopati No.47, Kebayoran',
      district: 'Jakarta Selatan',
      latitude: -6.2378,
      longitude: 106.8095,
      rating: 4.7,
      reviewCount: 892,
      priceRange: 'Rp 200k – 500k',
      openHours: '11:00 – 22:00',
      isOpen: true,
      isNew: true,
      imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
      phone: '+62 21 7278 1234',
      description: 'Fine dining modern dengan menu masakan Nusantara yang dielaborasi dengan teknik kontemporer.',
      tags: ['Fine Dining', 'Nusantara', 'Instagramable', 'Reservasi'],
      distanceKm: 5.2,
      amenities: ['Reservasi Wajib', 'Private Room', 'Wine List', 'Valet'],
    ),
    Place(
      id: 'p010',
      name: 'SOMA Wellness Jakarta',
      category: 'spa',
      subcategory: 'Massage & Reflexology',
      address: 'Agora Mall L2 #11, Thamrin',
      district: 'Jakarta Pusat',
      latitude: -6.1988,
      longitude: 106.8211,
      rating: 4.9,
      reviewCount: 196,
      priceRange: 'Rp 120k – 350k',
      openHours: '10:00 – 00:00',
      isOpen: true,
      isNew: true,
      imageUrl: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800',
      phone: '+62 815-1084-0518',
      description: 'Spa modern di dalam mall dengan jam operasional hingga tengah malam. Cocok untuk relaksasi setelah kerja.',
      tags: ['Buka Tengah Malam', 'Mall', 'Terjangkau', 'Modern'],
      distanceKm: 2.8,
      amenities: ['Di Dalam Mall', 'Late Night', 'Kartu Kredit', 'Booking Online'],
    ),
  ];

  static final List<Event> events = [
    Event(
      id: 'e001',
      title: 'Jakarta Food Festival 2025',
      description: 'Festival kuliner terbesar di Indonesia dengan 200+ tenant dari seluruh Nusantara.',
      location: 'Gelora Bung Karno, Senayan',
      district: 'Jakarta Pusat',
      startDate: DateTime(2025, 5, 10),
      endDate: DateTime(2025, 5, 18),
      imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
      category: 'food',
      priceRange: 'Rp 50k',
      interestedCount: 12450,
    ),
    Event(
      id: 'e002',
      title: 'Jak-Japan Matsuri',
      description: 'Festival budaya Jepang tahunan di Jakarta dengan pertunjukan, cosplay, dan kuliner khas.',
      location: 'Lapangan Banteng, Gambir',
      district: 'Jakarta Pusat',
      startDate: DateTime(2025, 5, 24),
      endDate: DateTime(2025, 5, 25),
      imageUrl: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800',
      category: 'entertainment',
      priceRange: 'Gratis',
      isFree: true,
      interestedCount: 8930,
    ),
    Event(
      id: 'e003',
      title: 'Jakarta Night Run 2025',
      description: 'Lari malam melewati ikon-ikon bersejarah Jakarta. Jarak 5K dan 10K tersedia.',
      location: 'Monas, Jakarta Pusat',
      district: 'Jakarta Pusat',
      startDate: DateTime(2025, 6, 7),
      endDate: DateTime(2025, 6, 7),
      imageUrl: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800',
      category: 'nature',
      priceRange: 'Rp 150k – 250k',
      interestedCount: 5670,
    ),
    Event(
      id: 'e004',
      title: 'Konser Dewa 19 Reunion',
      description: 'Reuni legendaris Dewa 19 di Jakarta setelah 10 tahun vakum.',
      location: 'Indonesia Arena, Senayan',
      district: 'Jakarta Selatan',
      startDate: DateTime(2025, 6, 21),
      endDate: DateTime(2025, 6, 21),
      imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
      category: 'nightlife',
      priceRange: 'Rp 350k – 2jt',
      interestedCount: 24000,
    ),
  ];

  static List<Place> getByCategory(String categoryId) {
    if (categoryId == 'all') return places;
    return places.where((p) => p.category == categoryId).toList();
  }

  static List<Place> getFeatured() {
    return places.where((p) => p.isFeatured).toList();
  }

  static List<Place> getNew() {
    return places.where((p) => p.isNew).toList();
  }

  static List<Place> search(String query) {
    final q = query.toLowerCase();
    return places.where((p) =>
      p.name.toLowerCase().contains(q) ||
      p.subcategory.toLowerCase().contains(q) ||
      p.district.toLowerCase().contains(q) ||
      p.tags.any((t) => t.toLowerCase().contains(q))
    ).toList();
  }
}
